FROM 153479249734.dkr.ecr.us-east-2.amazonaws.com/sar:zed_galatic


ARG ROS_PKG=ros_base
ENV ROS_DISTRO=galactic
ENV ROS_ROOT=/opt/ros/${ROS_DISTRO}
# ENV ROS_PYTHON_VERSION=3

SHELL ["/bin/bash", "-c"]
ENV SHELL /bin/bash

ENV ROS_WS /zed2_ws
RUN mkdir -p ${ROS_WS}/src

ENV DEBIAN_FRONTEND=noninteractive
ARG MAKEFLAGS=-j$(nproc)
ENV LANG=en_US.UTF-8
ENV PYTHONIOENCODING=utf-8
RUN locale-gen en_US en_US.UTF-8 && update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8


# ZED SDK / zed-ros2-wrapper
# https://github.com/stereolabs/zed-docker/blob/master/3.X/jetpack_4.X/devel/Dockerfile
#
ARG ZED_SDK_URL="https://download.stereolabs.com/zedsdk/3.7/jp46/jetsons"
ARG ZED_SDK_RUN="ZED_SDK_Tegra_JP46_v3.7.0.run"

RUN cd /tmp && \
    wget --quiet --show-progress --progress=bar:force:noscroll --no-check-certificate ${ZED_SDK_URL} -O ${ZED_SDK_RUN} && \
    chmod +x ${ZED_SDK_RUN} && \
    ./${ZED_SDK_RUN} -- silent && \
    rm -rf ${ZED_SDK_RUN} && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean && \
    ZED_Diagnostic -ais 8

RUN cd ${ROS_WS}/src/ &&\
git clone https://github.com/debanik123/zed-ros2-wrapper.git && \
git clone -b galactic https://github.com/ros-perception/image_common.git && \
git clone https://github.com/stereolabs/zed-ros2-interfaces.git && \
git clone -b galactic https://github.com/ros/diagnostics.git && \
git clone -b ros2 https://github.com/ros/xacro.git && \
git clone -b galactic https://github.com/ros-planning/navigation_msgs.git && \
git clone -b galactic https://github.com/ros2/geometry2.git && \
git clone -b galactic https://github.com/ros2/common_interfaces.git

# Manually pull dependencies for zed-ros2-wrapper
RUN cd ${ROS_WS} && \
source ${ROS_ROOT}/install/setup.bash && \
apt-get update && \
source ${ROS_ROOT}/install/setup.bash && \
colcon build --symlink-install --cmake-args=-DCMAKE_BUILD_TYPE=Release

#This symbolic link is needed to use the streaming features on Jetson inside a container
RUN ln -sf /usr/lib/aarch64-linux-gnu/tegra/libv4l2.so.0 /usr/lib/aarch64-linux-gnu/libv4l2.so
