FROM 153479249734.dkr.ecr.us-east-2.amazonaws.com/sar:foxy-ros-base-l4t-r32.6.1

RUN apt-get update && apt-get install -y \
    sshpass \
    git \
    sudo \
    build-essential \
    && pip3 install -U jetson-stats \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean
