shutdown_costmaps: false
#base_global_planner: "global_planner/GlobalPlanner"
controller_frequency: 20.0 #12 #1.2
planner_patience: 0.0
controller_patience: 10.0 #15.0
conservative_reset_dist: 3.0
planner_frequency: 5.0 #12 #1.2
oscillation_timeout: 15.0  #10.0
oscillation_distance: 0.2 #0.2
footprint_padding: 0.01
recovery_behaviors:
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
#conservative_reset:
#  reset_distance: 1.0
#  layer_names: ['obstacle_layer','range_layer']
#aggressive_reset:
#  reset_distance: 0.0
#  layer_names: ['obstacle_layer', 'range_layer']
#base_local_planner: "teb_local_planner/TebLocalPlannerROS"
