plugins:
   - {name: costmap_prohibition_layer,type: "costmap_prohibition_layer_namespace::CostmapProhibitionLayer"}
 #  - {name: costmap_prohibition_layer,type: costmap_prohibition_layer_namespace::CostmapProhibitionLayer"}
#   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}


prohibition_areas:
 # your first prohibited area is only a point
 - [[-5.4, 4.1],
    [-2.21,4,12],
    [-4.4,-4.4],
    [-7.1,-4.1]]
