core0_control:
  ros__parameters:
    use_sim_time: False
    K: 542.55
    w: 0.472

core0_odom:
  ros__parameters:
    use_sim_time: False
    odom_tf_pub: False
    ticks_meter: 3185.0
    base_width: 0.465
    rate: 10.0
