# Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Head Joint Controller
head_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: head_joint
