TebLocalPlannerROS:

   costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSMCCH"
   costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSConcaveHull"
   costmap_converter_spin_thread: True
   costmap_converter_rate: 5

   costmap_converter/CostmapToPolygonsDBSMCCH:
     cluster_max_distance: 0.4
     cluster_min_pts: 2
     cluster_max_pts: 30
     convex_hull_min_pt_separation: 0.1

   costmap_converter/CostmapToPolygonsDBSConcaveHull:
     cluster_max_distance: 0.4
     cluster_min_pts: 2
     cluster_max_pts: 30
     convex_hull_min_pt_separation: 0.1
     concave_hull_depth: 2.0
