FROM 153479249734.dkr.ecr.us-east-2.amazonaws.com/sar:foxy-ros-base-l4t-r32.6.1

ENV ROS_WS /rviz2_ws
RUN mkdir -p ${ROS_WS}/src

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
	libxaw7-dev \
	libxrandr-dev \
	libfreetype6-dev \
	qt5-default \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

RUN bash -c "cd ${ROS_WS}/src/ \
&& source /opt/ros/foxy/install/setup.bash \
&& git clone -b foxy https://github.com/ros/resource_retriever.git \
&& git clone -b foxy https://github.com/ros2/rviz.git \
&& git clone -b foxy https://github.com/ros-visualization/interactive_markers \
&& git clone -b foxy https://github.com/ros-perception/laser_geometry \
&& git clone -b debian/foxy/map_msgs https://github.com/ros2-gbp/navigation_msgs-release.git"

RUN bash -c "cd ${ROS_WS} \
&& source /opt/ros/foxy/install/setup.bash \
&& apt-get update \
&& rosdep install -q -y -r --from-paths src --ignore-src --rosdistro=foxy -y \
&& colcon build --symlink-install \
&& source install/setup.bash"

