FROM 153479249734.dkr.ecr.us-east-2.amazonaws.com/sar:foxy-ros-base-l4t-r32.6.1

ARG ROS_PKG=ros_base
ENV ROS_DISTRO=eloquent
ENV ROS_ROOT=/opt/ros/${ROS_DISTRO}

ENV DEBIAN_FRONTEND=noninteractive
ENV SHELL /bin/bash
SHELL ["/bin/bash", "-c"] 

WORKDIR /tmp

# change the locale from POSIX to UTF-8
RUN locale-gen en_US en_US.UTF-8 && update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV PYTHONIOENCODING=utf-8

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
		curl \
		wget \
		gnupg2 \
		lsb-release \
		ca-certificates \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean


RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
RUN sh -c 'echo "deb [arch=$(dpkg --print-architecture)] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
		build-essential \
		cmake \
		git \
		libbullet-dev \
		libpython3-dev \
		python3-colcon-common-extensions \
		python3-flake8 \
		python3-pip \
		python3-numpy \
		python3-pytest-cov \
		python3-rosdep \
		python3-setuptools \
		python3-vcstool \
		python3-rosinstall-generator \
		libasio-dev \
		libtinyxml2-dev \
		libcunit1-dev \
		libgazebo9-dev \
		gazebo9 \
		gazebo9-common \
		gazebo9-plugin-base \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

# install some pip packages needed for testing
RUN python3 -m pip install -U \
		argcomplete \
		flake8-blind-except \
		flake8-builtins \
		flake8-class-newline \
		flake8-comprehensions \
		flake8-deprecated \
		flake8-docstrings \
		flake8-import-order \
		flake8-quotes \
		pytest-repeat \
		pytest-rerunfailures \
		pytest

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ros-eloquent-ros-base \
    ros-eloquent-teleop-twist-keyboard \
    ros-eloquent-joint-state-publisher \
    ros-eloquent-robot-state-publisher \
    ros-eloquent-slam-toolbox \
    ros-eloquent-navigation2 \
    ros-eloquent-nav2-bringup \
    && rm -rf /var/lib/apt/lists/*


ENV ROS_WS /ros2_ws
RUN mkdir -p ${ROS_WS}/src
COPY ./packages/ros2_src/ros2_bot ${ROS_WS}/src

RUN bash -c "cd ${ROS_WS}\
&& source /opt/ros/eloquent/setup.bash\
&& colcon build --symlink-install"

COPY ./packages/ros_entrypoint.sh /ros_entrypoint.sh

RUN echo 'source ${ROS_ROOT}/setup.bash' >> /root/.bashrc

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]

WORKDIR /
