controller_manager:
  ros__parameters:
    update_rate: 10

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    core0_base_controller:
      type: diff_drive_controller/DiffDriveController
      
core0_base_controller:
  ros__parameters:
    left_wheel_names: ["left_drive_wheel_joint"]
    right_wheel_names: ["right_drive_wheel_joint"]

    wheel_separation: 0.454
    wheel_radius: 0.075

    # command_interface: left_drive_wheel_joint/velocity
    command_interfaces:
      - left_drive_wheel_joint/velocity

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_footprint

    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]

    open_loop: true
    enable_odom_tf: False

    cmd_vel_timeout: 0.5
    use_stamped_vel: false

    preserve_turning_radius: true

    publish_cmd: true
    publish_wheel_data: true

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 2.0
    linear.x.min_velocity: -2.0
    linear.x.max_acceleration: 20.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 4.0
    angular.z.min_velocity: -4.0
    angular.z.max_acceleration: 25.0
    angular.z.min_acceleration: -25.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0

    