global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 10.0 #1.2
  publish_frequency: 10.0 #1.2

  transform_tolerance: 4.0 # 0.25 seconds of latency, if greater than this, planner will stop
  rolling_window: true # Follow robot while navigating
  resolution: 0.05
  width: 30
  height: 30
  allow_unknown: true
  use_dijkstra: true
  use_quadratic: true
  use_grid_path: false
  old_navfn_behavior: false
  visualize_potential: true
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: lidar_link, data_type: LaserScan, topic: scan, marking: true, clearing: true, inf_is_valid: true, obstacle_range: 3, raytrace_range: 8}

  inflation_layer: {inflation_radius: 0.7, cost_scaling_factor: 3.0 }
#  obstacle_layer:
#    observation_sources: laser_scan_sensor
#    obstacle_range: 7.0
#    raytrace_range: 8
#    laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}
  static_layer: {enabled: true}
#  range_layer: {enabled: true, topics: [/sonar_1,/sonar_2,/sonar_3,/sonar_4,/sonar_5,/sonar_6,/sonar_7,/sonar_8],  no_readings_timeout: 5.0, clear_on_max_reading: true, clear_threshold: 0.3, mark_threshold: 0.9, expected_update_rate: 0.5}

  plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
#  - {name: range_layer, type: "range_sensor_layer::RangeSensorLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
#  - {name: costmap_prohibition_layer, type: "costmap_prohibition_layer_namespace::CostmapProhibitionLayer"}
