local_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 10.0  #1.0 #0.2
  publish_frequency: 10.0 #1.2
#  transform_tolerance: 1.0 # 0.25 seconds of latency, if greater than this, planner will stop
  rolling_window: true # Follow robot while navigating
  width: 4
  height: 4
  resolution: 0.1
  min_obstacle_height: -0.1
#  footprint: [[-0.47, -0.25], [-0.47, 0.25], [0.23, 0.25], [0.23, -0.25]]
#  footprint: [[-0.58, -0.25], [-0.58, 0.25], [0.12, 0.25], [0.12, -0.25]]
#  footprint: [[-0.35, -0.25], [-0.35, 0.25], [0.4, 0.25], [0.4, -0.25]]

  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: lidar_link, data_type: LaserScan, topic: scan, marking: true, clearing: true, inf_is_valid: true, obstacle_range: 3, raytrace_range: 8}

  inflation_layer: {inflation_radius: 0.7, cost_scaling_factor: 3.0 }
  obstacle_layer:
    observation_sources: laser_scan_sensor
    obstacle_range: 4
    raytrace_range: 5
    laser_scan_sensor: {sensor_frame: lidar_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}
#  range_layer: {enabled: true, topics: [/sonar_1,/sonar_2,/sonar_3,/sonar_4,/sonar_5,/m_sonar_1,/m_sonar_2,/m_sonar_3,/m_sonar_4,/m_sonar_5],  no_readings_timeout: 5.0, clear_on_max_reading: true, clear_threshold: 0.3, mark_threshold: 0.9, expected_update_rate: 0.5}

  plugins:
  - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
  - {name: range_layer,   type: "range_sensor_layer::RangeSensorLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
